# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d09669915f63d5fed1a9eb19ebb371ddb9c4c718fd390a772289a0370752395f115cf96d699c9c7dc6752dc1d3313024e18723cf294f177c07c9a0f1fefdede
  # secret_key_base: 2e09669915f63d5fed1a9eb19ebb371ddb9c4c718fd390a772289a0370752395f115cf96d699c9c7dc6752dc1d3313024e18723cf294f177c07c9a0f1fefbcbc

test:
  secret_key_base: 74c0bc565c288ec669a3b02247a56d958f659b7b2a834635c84075e958f69b920657706d6da96385f3413756384766fe8ee22dfe63a9e9fcab2b316295118bd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
